---
title: "Untitled"
output: html_document
date: "2023-09-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
setwd("C:/Users/deani/Desktop/Specialeprojekt")
getwd()
x <- read.table("fastANI_new.txt") #read the fastANI output file
```

# Code to produce the heatmap is from here:
https://github.com/spencer411/FastANI_heatmap


```{r}
library("reshape2")
library("ComplexHeatmap")
library("gplots")
library("fpc")
library("dbscan")
library("factoextra")
library(dplyr)
library(tidyverse)
```

```{r}
### convert data to matrix
matrix <- acast(x, V1~V2, value.var="V3")
matrix[is.na(matrix)] <- 70

#x
#matrix
```

```{r}
### define the colors within 2 zones
breaks = seq(min(matrix), max(100), length.out=100)
gradient1 = colorpanel( sum( breaks[-1]<=95 ), "red", "white" )
gradient2 = colorpanel( sum( breaks[-1]>95 & breaks[-1]<=100), "white", "blue" )

hm.colors = c(gradient1, gradient2)
heatmap.2(matrix, scale = "none", trace = "none", col = hm.colors, cexRow=.30, cexCol=.30)
```

## Dereplication of assumed clones

```{r}
z <- x %>% filter(V3 >99) %>% filter(V1 != V2) #filter for ANI >99% and remove same-genome-comparisons
z
```

# Export the data

```{r}
write.table(z, file = "ANI_99.tsv", sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)

M <- as.data.frame(matrix)
write.table(M, file = "ANI_matrix.tsv", sep = "\t", row.names = TRUE, col.names = TRUE, quote = FALSE)
```



## Clustering (DBSCAN) of the genomes based on ANI

```{r}
# Step 2: Perform DBSCAN
# Specify the DBSCAN parameters
eps <- 23  # Adjust as needed
minPts <- 5  # Adjust as needed

# Perform DBSCAN clustering
dbscan_result <- dbscan(matrix, eps = eps, MinPts = minPts)

dbscan_result

# Step 3: Inspect the Clusters
# Get the cluster labels
cluster_labels <- dbscan_result$cluster

# Step 4: Visualize the Clustering
# Convert the data to a data frame
data_df <- as.data.frame(matrix)
data_df$Cluster <- factor(cluster_labels)

data_df %>% mutate(sequence_ID = rownames(data_df)) %>% relocate(sequence_ID) %>% as_tibble() %>% select(sequence_ID, Cluster) %>% mutate(strain = str_extract(sequence_ID, pattern = "22.*-[0-9]{1,2}")) %>% select(strain, Cluster)

```







```{r}
dbscan::kNNdistplot(matrix, k =  5)
abline(h = 0.15, lty = 2)
```

## Producing a PCA plot

```{r}
pca <- prcomp(matrix,
                   center = TRUE,
                   scale. = TRUE)
  
# summary of the prcomp object
#summary(pca)
```

```{r}
# loading library
library(ggfortify)
pca.plot <- autoplot(pca, data = matrix)
  
pca.plot
```
