---
title: "Untitled"
output: html_document
date: "2024-01-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("C:/Users/deani/Desktop/Specialeprojekt")
getwd()
x <- read.table("fastANI_75/75_polished_ANI_out.txt") #read the fastANI output file

x$V1 <- sub("_polished_sorted.fasta", "", x$V1)
x$V2 <- sub("_polished_sorted.fasta", "", x$V2)
```

# Code to produce the heatmap is from here:
https://github.com/spencer411/FastANI_heatmap


```{r}
library("reshape2")
library("ComplexHeatmap")
library("gplots")
library("fpc")
library("dbscan")
library("factoextra")
library(dplyr)
library(tidyverse)
library(ape)
library(phangorn)
```

```{r}
### convert data to matrix
matrix <- acast(x, V1~V2, value.var="V3")
matrix[is.na(matrix)] <- 70

```


```{r}
### define the colors within 2 zones
breaks = seq(min(matrix), max(100), length.out=100)
gradient1 = colorpanel( sum( breaks[-1]<=95 ), "red", "white" )
gradient2 = colorpanel( sum( breaks[-1]>95 & breaks[-1]<=100), "white", "blue" )

?heatmap.2

hm.colors = c(gradient1, gradient2)
heatmap.2(matrix, scale = "none", trace = "none", col = hm.colors, labRow=FALSE, labCol = FALSE)
```











